include:
  template: SAST.gitlab-ci.yml
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
    - build
    - test
    
build:
    stage: build
    script:
        - make -j$(nproc --all)
    artifacts:
        paths:
            - build

testsuite:
    image: "git.fh-muenster.de:4567/dk426722/libosmp:latest"
    stage: test
    script:
        - python3 testsuite/testit.py
        
mem_test:
    image: "git.fh-muenster.de:4567/dk426722/libosmp:latest"
    stage: test
    script:
        - valgrind --error-exitcode=2 ./build/osmprun
